### ISSUE TITLE
neurolibre.conp.ca currently links to mybinder, not binder.conp.cloud

### ISSUE THREAD

**Issue by lunebellec** [neurolibre/neurolibre-binderhub#14]
at least for the T1 MRI notebook, and the nilearn notebooks.

**Comment by emdupre** [comment]
I think this is leftover from when we moved them there for the April demo (see https://github.com/neurolibre/introML-book/commit/ca1672c8fe715e0fa61390f0034589b432acc78d, since our binderhub wasn't working at the time). Moving them back should be as easy as changing this line:

https://github.com/neurolibre/introML-book/blob/1cb58e060ad94f32176a4acb8aeac7f72be398e1/_config.yml#L61

In each of the relevant repositories.

**Comment by ltetrel** [comment]
This will be updated when the website https://github.com/neurolibre/neurolibre.com will be up
